Repository VorTECHsa/python-sdk, pull requests merged in 2022-11, with the labels that each got.

#397 Feat voyages dwtcbm
  vortexasdk/endpoints/voyages_congestion_breakdown.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/endpoints/voyages_top_hits.py
  vortexasdk/version.py
Labels: echoes/effort: S

#393 refactor: use warn over assert
  vortexasdk/client.py
  vortexasdk/version.py
Labels: echoes/effort: S, echoes/intent: bug

#396 add controller param
  docs/examples/China_Flows.ipynb
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/endpoints/destination_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_avg_distance_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_capacity_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_destination_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_origin_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_quantity_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_speed_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_timeseries.py
  vortexasdk/endpoints/origin_breakdown.py
  vortexasdk/endpoints/tonne_miles_breakdown.py
  vortexasdk/endpoints/vessel_availability_breakdown.py
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/endpoints/vessel_availability_timeseries.py
  vortexasdk/endpoints/vessel_movements.py
  vortexasdk/version.py
Labels: echoes/effort: S

#403 Rnd 24 cargo move
  tests/endpoints/test_cargo_movements_real.py
  vortexasdk/client.py
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/endpoints.py
  vortexasdk/operations.py
  vortexasdk/version.py
Labels: echoes/intent: improvement
