Repository VorTECHsa/python-sdk, pull requests merged in 2022-12, with the labels that each got.

#405 debt: drop time series activity time params for cm
  tests/endpoints/test_cargo_movements_real.py
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/version.py
Labels: echoes/effort: XS, echoes/intent: tech-debt

#406 Freight metrics docs
  .circleci/config.yml
  docs/endpoints/freight-metrics/avg-distance.md
  docs/endpoints/freight-metrics/avg-speed.md
  docs/endpoints/freight-metrics/capacity.md
  docs/endpoints/freight-metrics/destination.md
  docs/endpoints/freight-metrics/dwt.md
  docs/endpoints/freight-metrics/origin.md
  docs/endpoints/freight-metrics/quantity.md
  docs/endpoints/freight-metrics/tonne-miles.md
  docs/endpoints/freight-metrics/utilisation.md
  mkdocs.yml
  pydocmd.yml
  vortexasdk/endpoints/fleet_utilisation_avg_distance_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_capacity_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_destination_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_origin_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_quantity_timeseries.py
  vortexasdk/endpoints/fleet_utilisation_speed_breakdown.py
  vortexasdk/endpoints/fleet_utilisation_timeseries.py
  vortexasdk/endpoints/tonne_miles_breakdown.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt

#407 Fix broken link to timeseries
  docs/endpoints/freight-metrics/avg-distance.md
  docs/endpoints/freight-metrics/avg-speed.md
  docs/endpoints/freight-metrics/capacity.md
  docs/endpoints/freight-metrics/dwt.md
  docs/endpoints/freight-metrics/quantity.md
  docs/endpoints/freight-metrics/tonne-miles.md
  docs/endpoints/freight-metrics/utilisation.md
  vortexasdk/version.py
Labels: echoes/intent: bug
