Repository VorTECHsa/python-sdk, pull requests merged in 2023-11, with the labels that each got.

#457 Chore onshore search after
  vortexasdk/endpoints/onshore_inventories_result.py
  vortexasdk/endpoints/onshore_inventories_search.py
  vortexasdk/version.py
Labels: echoes/intent: improvement

#458 feat(vessel-summary): add vessel summary endpoint to sdk
  .vscode/settings.json
  README.md
  docs/examples/try_me_out/vessel_summary.ipynb
  pydocmd.yml
  vortexasdk/__init__.py
  vortexasdk/api/__init__.py
  vortexasdk/api/vessel_summary.py
  vortexasdk/endpoints/__init__.py
  vortexasdk/endpoints/endpoints.py
  vortexasdk/endpoints/vessel_summary.py
  vortexasdk/endpoints/vessel_summary_result.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: M, echoes/intent: feedback

#459 chore(docs): summary link
  mkdocs.yml
  vortexasdk/version.py
Labels: echoes/effort: XS, echoes/intent: feedback
