Repository VorTECHsa/python-sdk, pull requests merged in 2023-09, with the labels that each got.

#441 Remove warning log for search after implementation
  vortexasdk/client.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: XS

#442 Include new vessel classes properties
  tests/api/examples/cargo_movements.json
  tests/api/examples/vessel_entity1.json
  tests/api/examples/vessels.json
  tests/api/test_cargo_movement.py
  tests/api/test_vessel_entity.py
  tests/endpoints/test_vessels_search_result.py
  vortexasdk/api/shared_types.py
  vortexasdk/api/vessel.py
  vortexasdk/api/vessel_availability.py
  vortexasdk/api/voyages.py
  vortexasdk/version.py
Labels: echoes/effort: M, echoes/intent: feedback

#444 chore: add file to notebook
  docs/examples/Financial_service_SDK_use_cases.ipynb
  docs/examples/jupyter_notebooks.md
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS, echoes/intent: feedback

#445 Debt remove vm links
  mkdocs.yml
  pydocmd.yml
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: XS, echoes/intent: feedback

#446 Include new vessel class parameters into the Supported lists of values
  vortexasdk/endpoints/vessels.py
  vortexasdk/version.py
Labels: echoes/effort: S, echoes/intent: feedback

#447 update: requests package version
  setup.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/intent: tech-debt, echoes/effort: XS, echoes/intent: feedback

#448 Add new values in vessel classes documentation
  vortexasdk/endpoints/vessels.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S, echoes/intent: feedback

#450 Feat va filters
  tests/endpoints/test_availability.py
  vortexasdk/api/vessel_availability.py
  vortexasdk/endpoints/vessel_availability_breakdown.py
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/endpoints/vessel_availability_timeseries.py
  vortexasdk/version.py
Labels: echoes/effort: S, echoes/intent: feedback

#451 chore: remove unused fields
  vortexasdk/api/onshore_inventory.py
  vortexasdk/endpoints/asset_tanks.py
  vortexasdk/endpoints/onshore_inventories_result.py
  vortexasdk/endpoints/onshore_inventories_search.py
  vortexasdk/endpoints/onshore_inventories_timeseries.py
  vortexasdk/version.py
Labels: documentation, enhancement, impact: medium, impact: low, echoes/intent: improvement, echoes/intent: tech-debt, echoes/effort: S, echoes/effort: XS, echoes/impedement

#452 [RND-3905] feat: flatten all events
  vortexasdk/api/entity_flattening.py
  vortexasdk/version.py
Labels: echoes/intent: bug
