Repository VorTECHsa/python-sdk, pull requests merged in 2023-02, with the labels that each got.

#414 Update description
  vortexasdk/endpoints/onshore_inventories_result.py
  vortexasdk/endpoints/voyages_congestion_breakdown_result.py
  vortexasdk/endpoints/voyages_search_enriched.py
  vortexasdk/endpoints/voyages_search_enriched_result.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS

#415 docs: update vm deprecations note
  vortexasdk/endpoints/vessel_movements.py
  vortexasdk/version.py
Labels: documentation, echoes/intent: improvement, echoes/effort: XS

#416 feat: update python docs
  vortexasdk/endpoints/voyages_search_enriched.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#418 Docs: Add missing state in filter activity for cargo movements
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: S

#419 Remove legacy endpoints from the docs
  mkdocs.yml
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: XS
