Repository VorTECHsa/python-sdk, pull requests merged in 2023-10, with the labels that each got.

#453 [RND-3721] Fix fixtures columns
  vortexasdk/endpoints/fixtures_result.py
  vortexasdk/version.py
Labels: echoes/intent: bug

#454 Intra movements filter
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/endpoints/destination_breakdown.py
  vortexasdk/endpoints/movement_status_breakdown.py
  vortexasdk/endpoints/origin_breakdown.py
  vortexasdk/endpoints/parent_product_breakdown.py
  vortexasdk/endpoints/product_breakdown.py
  vortexasdk/endpoints/vessel_class_breakdown.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#455 Chore update onshore
  README.md
  tests/endpoints/test_onshore_inventories_search.py
  vortexasdk/endpoints/onshore_inventories_search.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#456 feat(voyages): add voyage_status to the response of search
  vortexasdk/api/voyages.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS
