Repository VorTECHsa/python-sdk, pull requests merged in 2024-04, with the labels that each got.

#483 chore: cargos docs updated - `waypoint` activity filters, time-series breakdown
  tests/endpoints/test_vessel_class_breakdown.py
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS

#485 chore: added binder links
  vortexasdk/endpoints/canal_transit.py
  vortexasdk/endpoints/canal_transit_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS

#486 feat: support none and empty string next request header
  tests/endpoints/test_canal_transit_real.py
  vortexasdk/client.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: S

#490 Type vessel tags
  vortexasdk/endpoints/voyages_search_enriched.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: S

#491 Remove offset support from SDK
  tests/mock_client.py
  vortexasdk/client.py
  vortexasdk/endpoints/canal_transit.py
  vortexasdk/endpoints/canal_transit_timeseries.py
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/freight_pricing_search.py
  vortexasdk/endpoints/onshore_inventories_search.py
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/endpoints/voyages_search_enriched.py
  vortexasdk/operations.py
  vortexasdk/utils.py
  vortexasdk/version.py
Labels: echoes/effort: M, echoes/intent: feedback

#492 Include missing voyage filters
  tests/endpoints/test_voyages_search_enriched.py
  tests/endpoints/test_voyages_timeseries.py
  vortexasdk/api/__init__.py
  vortexasdk/api/shared_types.py
  vortexasdk/api/voyages.py
  vortexasdk/endpoints/voyages_congestion_breakdown.py
  vortexasdk/endpoints/voyages_geography_breakdown.py
  vortexasdk/endpoints/voyages_product_breakdown.py
  vortexasdk/endpoints/voyages_routes_breakdown.py
  vortexasdk/endpoints/voyages_search_enriched.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/endpoints/voyages_timeseries_v2.py
  vortexasdk/endpoints/voyages_top_hits.py
  vortexasdk/endpoints/voyages_vessel_class_breakdown.py
  vortexasdk/utils.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: S, echoes/intent: feedback

#494 Remove filterable from corporate entities records
  tests/api/examples/corporations.json
  vortexasdk/api/corporation.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt
