Repository VorTECHsa/python-sdk, pull requests merged in 2024-02, with the labels that each got.

#470 Rnd 5459 - Fix timeseries to have correct labels and values
  tests/endpoints/test_onshore_inventories_timeseries.py
  vortexasdk/endpoints/timeseries_result.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#473 feat: vessels commercials filters
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#476 Rnd 5313
  docs/endpoints/about-endpoints.md
  docs/examples/1_china.py
  docs/examples/SDK Cookbook.ipynb
  docs/examples/academy/19. Querying the SDK.ipynb
  docs/examples/academy/25. Filtering by Vessel.ipynb
  tests/endpoints/test_availability.py
  tests/endpoints/test_cargo_movements_real.py
  tests/endpoints/test_cargo_time_series_real.py
  tests/endpoints/test_vessel_class_breakdown.py
  tests/endpoints/test_vessels_real.py
  vortexasdk/endpoints/cargo_movements.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/endpoints/vessel_summary.py
  vortexasdk/endpoints/vessels.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/endpoints/voyages_top_hits.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS

#477 fix: geography breakdown try me out
  docs/examples/try_me_out/voyages_geography_breakdown.ipynb
  vortexasdk/version.py
Labels: documentation, echoes/effort: XS

#478 fix: remove oil_aframax_lr3
  vortexasdk/endpoints/vessel_summary.py
  vortexasdk/endpoints/vessels.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: XS

#474 doc: include new route for LNG
  vortexasdk/endpoints/freight_pricing_search.py
  vortexasdk/version.py
Labels: documentation, impact: low, echoes/effort: S, echoes/intent: feedback
