Repository VorTECHsa/python-sdk, pull requests merged in 2024-01, with the labels that each got.

#460 chore: remove default params
  tests/endpoints/test_voyages_congestion_breakdown.py
  vortexasdk/endpoints/onshore_inventories_search.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/intent: improvement

#461 fix: updated expired measurement_id
  tests/endpoints/test_onshore_inventories_search.py
Labels: echoes/intent: bug

#463 feat(VoyagesTimeseries): chunk multi state request
  tests/test_utils.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/utils.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: M

#464 fix: type of has_charterer & has_ship_to_ship
  tests/endpoints/test_voyages_search_enriched.py
  vortexasdk/endpoints/voyages_congestion_breakdown.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/endpoints/voyages_top_hits.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: XS

#465 Type hint Result().to_df()
  vortexasdk/api/entity_flattening.py
  vortexasdk/api/search_result.py
  vortexasdk/endpoints/aggregation_breakdown_result.py
  vortexasdk/endpoints/asset_tanks_result.py
  vortexasdk/endpoints/attributes_result.py
  vortexasdk/endpoints/breakdown_result.py
  vortexasdk/endpoints/cargo_movements_result.py
  vortexasdk/endpoints/corporations_result.py
  vortexasdk/endpoints/eia_forecasts_result.py
  vortexasdk/endpoints/fixtures_result.py
  vortexasdk/endpoints/freight_pricing_result.py
  vortexasdk/endpoints/geographies_result.py
  vortexasdk/endpoints/onshore_inventories_result.py
  vortexasdk/endpoints/products_result.py
  vortexasdk/endpoints/reference_breakdown_result.py
  vortexasdk/endpoints/storage_terminals_result.py
  vortexasdk/endpoints/timeseries_result.py
  vortexasdk/endpoints/vessel_availability_result.py
  vortexasdk/endpoints/vessel_summary_result.py
  vortexasdk/endpoints/vessels_result.py
  vortexasdk/endpoints/voyages_congestion_breakdown_result.py
  vortexasdk/result_conversions.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt

#462 Cargo ts splits
  tests/api/examples/cargo_time_series.json
  tests/endpoints/test_cargo_time_series.py
  tests/endpoints/test_cargo_time_series_real.py
  tests/endpoints/test_onshore_inventories_timeseries.py
  vortexasdk/endpoints/breakdown_result.py
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/endpoints/onshore_inventories_timeseries.py
  vortexasdk/endpoints/timeseries_result.py
  vortexasdk/endpoints/voyages_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: improvement

#468 feat: retry if response.code == 401
  vortexasdk/retry_session.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: S

#469 Remove reference data conversion util
  tests/conversions/__init__.py
  tests/conversions/test_conversions.py
  tests/conversions/test_convert_vessels.py
  vortexasdk/conversions/__init__.py
  vortexasdk/conversions/conversions.py
  vortexasdk/conversions/corporations.py
  vortexasdk/conversions/geographies.py
  vortexasdk/conversions/products.py
  vortexasdk/conversions/vessels.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/intent: tech-debt
