Repository VorTECHsa/python-sdk, pull requests merged in 2024-11, with the labels that each got.

#515 docs: update some docs for new shipping regions
  vortexasdk/endpoints/cargo_timeseries.py
  vortexasdk/endpoints/destination_breakdown.py
  vortexasdk/endpoints/geographies.py
  vortexasdk/endpoints/origin_breakdown.py
  vortexasdk/version.py
Labels: echoes/effort: XS, echoes/intent: feedback

#516 chore: update pr template
  .github/pull_request_template.md
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/intent: tech-debt, echoes/effort: XS

#518 docs: include `BLNG{1,2,3}-174` routes in freight pricing documentation
  vortexasdk/endpoints/freight_pricing_search.py
  vortexasdk/endpoints/freight_pricing_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS

#519 fix: updated_since default value fix
  vortexasdk/endpoints/canal_transit.py
  vortexasdk/version.py
Labels: bug, echoes/effort: S

#527 chore: bump resource class for tests
  .circleci/config.yml
Labels: echoes/intent: bug, echoes/intent: improvement, echoes/effort: XS

#528 chore: bump version -> 1.0.1
  vortexasdk/version.py
Labels: echoes/intent: improvement, echoes/effort: XS
