Repository VorTECHsa/python-sdk, pull requests merged in 2024-12, with the labels that each got.

#535 fix(doc): correct exclude param name of VA
  vortexasdk/endpoints/vessel_availability_breakdown.py
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/endpoints/vessel_availability_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: S

#537 Add new time params for vessel availability
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/version.py
Labels: echoes/effort: S, echoes/intent: feedback

#538 Fix issues with invalid dates provided in Vessel Availabilities
  tests/endpoints/test_availability_search.py
  vortexasdk/endpoints/vessel_availability_search.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: S
