Repository VorTECHsa/python-sdk, pull requests merged in 2024-05, with the labels that each got.

#496 Fix running Vortexa Python SDK on WSL2
  setup.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: XS

#498 Fix onshore inventories test
  docs/examples/academy/34. Hypothesis Testing I.ipynb
  docs/examples/academy/35. Hypothesis Testing II.ipynb
  tests/endpoints/test_onshore_inventories_timeseries.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: S

#497 Improve performance for TimeSeriesResult.to_df
  vortexasdk/endpoints/timeseries_result.py
  vortexasdk/version.py
Labels: echoes/intent: tech-debt, echoes/effort: M

#500 fix: check if key col exists
  vortexasdk/endpoints/timeseries_result.py
  vortexasdk/version.py
Labels: echoes/intent: bug, echoes/effort: S
